import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import { FloatingCTA } from "@/components/layout/FloatingCTA";
import { SchemaMarkup } from "@/components/shared/SchemaMarkup";
import { buildLocalBusinessSchema, buildWebSiteSchema } from "@/lib/schema";
import { SITE } from "@/lib/constants";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#2563EB" },
    { media: "(prefers-color-scheme: dark)", color: "#0F172A" },
  ],
  colorScheme: "light dark",
};

export const metadata: Metadata = {
  metadataBase: new URL(SITE.url),
  title: {
    default: `${SITE.name} | House Removals Wolverhampton | Man & Van | Free Quote`,
    template: `%s | ${SITE.name}`,
  },
  description:
    "Get Rapid Removals — Wolverhampton's trusted local removals company. Professional house removals, house clearance, man and van, office removals & packing services across Wolverhampton & the West Midlands. Fully insured, free quotes, same-day available. Call 07778 298447.",
  keywords: [
    "house removals Wolverhampton",
    "removal company Wolverhampton",
    "man and van Wolverhampton",
    "house clearance Wolverhampton",
    "office removals Wolverhampton",
    "moving company Wolverhampton",
    "furniture removals Wolverhampton",
    "same day removals Wolverhampton",
    "emergency removals Wolverhampton",
    "Get Rapid Removals",
    "removals West Midlands",
    "house clearance West Midlands",
  ],
  authors: [{ name: SITE.name, url: SITE.url }],
  creator: SITE.name,
  publisher: SITE.name,
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },
  openGraph: {
    type: "website",
    locale: "en_GB",
    url: SITE.url,
    siteName: SITE.name,
    title: `${SITE.name} | Wolverhampton's Most Trusted Removals Company`,
    description:
      "Professional house removals, house clearance & man and van services in Wolverhampton. Fully insured, 5-star rated, free quotes. Call 07778 298447.",
    images: [
      {
        url: `${SITE.url}/og-image.jpg`,
        width: 1200,
        height: 630,
        alt: `${SITE.name} — Wolverhampton Removals & Clearance`,
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: `${SITE.name} | House Removals Wolverhampton`,
    description:
      "Professional removals & house clearance in Wolverhampton. 5.0★ rated, fully insured, free quotes. Same day available.",
    images: [`${SITE.url}/og-image.jpg`],
  },
  alternates: {
    canonical: SITE.url,
    languages: {
      "en-GB": SITE.url,
      "x-default": SITE.url,
    },
  },
  verification: {
    google: "8wF_eexPI_YiE5ZafXEnotKqYPqFCvOXJdo-mVM7W3g",
  },
  category: "Business",
  icons: {
    icon: [
      // SVG — scales perfectly, served to modern browsers first
      { url: "/favicon.svg", type: "image/svg+xml" },
      // PNG fallback — generated by app/icon.tsx
      { url: "/icon", type: "image/png", sizes: "32x32" },
    ],
    apple: [
      // Apple Touch Icon — generated by app/apple-icon.tsx
      { url: "/apple-icon", type: "image/png", sizes: "180x180" },
    ],
    shortcut: [
      { url: "/favicon.svg", type: "image/svg+xml" },
    ],
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const schemas = [buildLocalBusinessSchema(), buildWebSiteSchema()];

  return (
    <html lang="en-GB" className={inter.variable}>
      <head>
        <SchemaMarkup schema={schemas} />
        {/* Favicon: SVG for modern browsers (scalable, theme-aware) */}
        <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
        {/* Safari pinned tab: solid single-colour version of the truck */}
        <link rel="mask-icon" href="/favicon.svg" color="#2563EB" />
        {/* Preconnect for Google Fonts */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
      </head>
      <body className="min-h-screen flex flex-col bg-white text-brand-dark">
        <Header />
        <main className="flex-1" id="main-content">
          {children}
        </main>
        <Footer />
        <FloatingCTA />
        {/* Skip to main content for accessibility */}
        <a
          href="#main-content"
          className="sr-only focus:not-sr-only focus:fixed focus:top-4 focus:left-4 focus:z-[9999] focus:bg-brand-blue focus:text-white focus:px-4 focus:py-2 focus:rounded-lg"
        >
          Skip to main content
        </a>
      </body>
    </html>
  );
}
